dependencies:
  - name: jenkins
    version: "*"
    repository: "alias:stable"
  - name: clair
    version: "*"
    repository: "file://./vendored_charts/clair"
  - name: docker-registry
    version: "*"
    repository: "file://./vendored_charts/docker-registry"
  - name: postgresql
    version: "*"
    condition: postgresql.enabled
    #repository: "alias:stable"
    repository: "file://./vendored_charts/postgresql"
